### model
# model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
model_name_or_path: /modeldatas/Meta-Llama-3-8B-Instruct
trust_remote_code: true

### method
stage: dpo
do_train: true
finetuning_type: full
deepspeed: /workspace/llamafactory-training/LLaMA-Factory/examples/deepspeed/ds_z2_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset_dir: /workspace/llamafactory-training/LLaMA-Factory/data
dataset: dpo_en_demo, dpo_zh_demo
template: llama3
cutoff_len: 2048
max_samples: 5000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3-3b/full/dpo
logging_steps: 10
save_steps: 5000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 5.0e-6
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500